const Alert = "Alert";
const REFETCH_CHATS = "REFATCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_Message = "NEW_Message";

const START_TYPING ="START_TYPING";
const STOP_TYPING ="STOP_TYPING";


export {
  Alert,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_Message,
  START_TYPING,
  STOP_TYPING
};
