const Alert = "Alert";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_Message = "NEW_Message";
const START_TYPING ="START_TYPING";
const STOP_TYPING ="STOP_TYPING";

const CHAT_JOINED ="CHAT_JOINED";
const CHAT_LEAVED ="CHAT_LEAVED";

const ONLINE_USERS="ONLINE_USERS";

export {
  Alert,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_Message,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS
};
