const Alert= "Alert";
const REFATCH_CHATS= "REFATCH_CHATS";

const NEW_ATTACHMENT= "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT= "NEW_MESSAGE_ALERT";
export  {Alert,REFATCH_CHATS,NEW_ATTACHMENT,NEW_MESSAGE_ALERT};
